theme: jekyll-theme-minimal
baseurl: ""
title: ZANARDI Bruno
description: >
  Software Developper<br/>
  <ul>
    <li><a href="{{ site.baseurl }}"Home</a></li>
    <li><a href="resume">Resume</a></li>
  </ul>
