theme: jekyll-theme-minimal
title: ZANARDI Bruno
description: >
  Software Developper<br/><br/>
  <a href="https://zanar.github.io">Home</a><br/>
  <a href="https://zanar.github.io/resume_h">Resume</a><br/><br/>
